services:
  mongodb:
    image: mongo:6.0
    container_name: ecommerce-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - ecommerce-network
    restart: unless-stopped
    command: mongod --noauth

volumes:
  mongodb_data:
    name: ecommerce-mongodb-data

networks:
  ecommerce-network:
    name: ecommerce-network
    driver: bridge